# Generated by Django 2.0.6 on 2019-06-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=255)),
                ('active', models.IntegerField(default=0)),
                ('verify_link', models.CharField(default=0, max_length=255)),
                ('log_in_time', models.CharField(default='', max_length=255)),
                ('log_out_time', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
